# Generated by Django 5.0.7 on 2024-07-27 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0002_leadnote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="discription",
            new_name="description",
        ),
    ]
