# Generated by Django 5.0.7 on 2024-07-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0003_rename_discription_lead_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="convert_to_client",
            field=models.BooleanField(default=False),
        ),
    ]
