# Generated by Django 5.0.7 on 2024-07-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0004_lead_convert_to_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="leadnote",
            name="first_name",
            field=models.CharField(default="efe", max_length=225),
            preserve_default=False,
        ),
    ]
