# Generated by Django 5.0.7 on 2024-07-28 20:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="description",
        ),
        migrations.RemoveField(
            model_name="client",
            name="email",
        ),
        migrations.RemoveField(
            model_name="client",
            name="name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="service",
        ),
        migrations.AddField(
            model_name="client",
            name="assigned_to",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="close_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="converted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="client",
            name="converted_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="converted_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="first_name",
            field=models.CharField(default="FirstNamePlaceholder", max_length=255),
        ),
        migrations.AddField(
            model_name="client",
            name="last_name",
            field=models.CharField(default="LastNamePlaceholder", max_length=255),
        ),
        migrations.AddField(
            model_name="client",
            name="middle_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="open_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="services",
            field=models.CharField(
                choices=[
                    ("POF", "POF"),
                    ("Insurance", "Insurance"),
                    ("Visa Processing", "Visa Processing"),
                    ("Admission processing", "Admission processing"),
                    ("Visa fee payment", "Visa fee payment"),
                ],
                default="Visa Processing",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                default="open",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="traffic_source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="ClientNote",
        ),
    ]
