# Generated by Django 5.0.7 on 2024-07-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_remove_client_description_remove_client_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(default="example@email.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
